server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/video/**
        - id: sentiment-service
          uri: lb://sentiment-service
          predicates:
            - Path=/api/sentiment/**
        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/api/recommendations/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus