# Prometheus configuration for comprehensive microservices monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'graphql-service'
    static_configs:
      - targets: ['graphql-service:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'ml-engine'
    static_configs:
      - targets: ['ml-engine:5000']
    metrics_path: '/metrics'

  - job_name: 'video-service'
    static_configs:
      - targets: ['video-service:5001']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']