# Netflix Conductor Workflow Orchestration
version: '3.8'

services:
  conductor-server:
    image: conductoross/conductor-server:3.15.0
    container_name: conductor-server
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PROP=config.properties
    volumes:
      - ./conductor-config:/app/config
    depends_on:
      - elasticsearch
      - redis
    networks:
      - streaming-network

  conductor-ui:
    image: conductoross/conductor-ui:3.15.0
    container_name: conductor-ui
    ports:
      - "5000:5000"
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    depends_on:
      - conductor-server
    networks:
      - streaming-network