server:
  port: 8080

spring:
  application:
    name: api-gateway
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health

zuul:
  routes:
    chat-service:
      path: /chat/**
      service-id: chat-service
      strip-prefix: false
    ml-engine:
      path: /ml/**
      service-id: ml-engine
      strip-prefix: false
    video-service:
      path: /video/**
      service-id: video-service
      strip-prefix: false
    graphql-service:
      path: /graphql/**
      service-id: graphql-service
      strip-prefix: false
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,hystrix.stream
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.netflix: DEBUG
    org.springframework.cloud: DEBUG