global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'eureka-server'
    static_configs:
      - targets: ['eureka-server:8761']
    metrics_path: '/actuator/prometheus'

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'video-service'
    static_configs:
      - targets: ['video-service:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'sentiment-service'
    static_configs:
      - targets: ['sentiment-service:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['recommendation-service:8084']
    metrics_path: '/actuator/prometheus'

  - job_name: 'ml-engine'
    static_configs:
      - targets: ['ml-engine:5000']