apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: streamsense
  labels:
    app: eureka-server
    tier: infrastructure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
        tier: infrastructure
    spec:
      containers:
      - name: eureka-server
        image: streamsense/eureka-server:latest
        ports:
        - containerPort: 8761
          name: eureka
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: EUREKA_INSTANCE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-server.streamsense.svc.cluster.local:8761/eureka/"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: streamsense
  labels:
    app: eureka-server
    tier: infrastructure
spec:
  ports:
  - port: 8761
    targetPort: 8761
    name: eureka
  selector:
    app: eureka-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: streamsense
  labels:
    app: config-server
    tier: infrastructure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
        tier: infrastructure
    spec:
      containers:
      - name: config-server
        image: streamsense/config-server:latest
        ports:
        - containerPort: 8888
          name: config
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: streamsense-config
              key: eureka.default.zone
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: streamsense
  labels:
    app: config-server
    tier: infrastructure
spec:
  ports:
  - port: 8888
    targetPort: 8888
    name: config
  selector:
    app: config-server
  type: ClusterIP