apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: streamsense
  labels:
    app: api-gateway
    tier: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        tier: gateway
    spec:
      containers:
      - name: api-gateway
        image: streamsense/api-gateway:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: streamsense-config
              key: eureka.default.zone
        - name: SPRING_ZIPKIN_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: streamsense-config
              key: zipkin.base.url
        resources:
          requests:
            memory: "768Mi"
            cpu: "400m"
          limits:
            memory: "1.5Gi"
            cpu: "800m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: streamsense
  labels:
    app: api-gateway
    tier: gateway
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: api-gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: streamsense
  labels:
    app: chat-service
    tier: microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
        tier: microservice
    spec:
      containers:
      - name: chat-service
        image: streamsense/chat-service:latest
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: streamsense-config
              key: eureka.default.zone
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: streamsense-config
              key: kafka.bootstrap.servers
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: streamsense-config
              key: redis.host
        - name: SPRING_ZIPKIN_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: streamsense-config
              key: zipkin.base.url
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: streamsense
  labels:
    app: chat-service
    tier: microservice
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  selector:
    app: chat-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-service
  namespace: streamsense
  labels:
    app: graphql-service
    tier: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: graphql-service
  template:
    metadata:
      labels:
        app: graphql-service
        tier: microservice
    spec:
      containers:
      - name: graphql-service
        image: streamsense/graphql-service:latest
        ports:
        - containerPort: 8086
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: streamsense-config
              key: eureka.default.zone
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres.streamsense.svc.cluster.local:5432/streaming_analytics"
        - name: SPRING_DATASOURCE_USERNAME
          value: "streaming_user"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: streamsense-secrets
              key: postgres-password
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  namespace: streamsense
  labels:
    app: graphql-service
    tier: microservice
spec:
  ports:
  - port: 8086
    targetPort: 8086
    name: http
  selector:
    app: graphql-service
  type: ClusterIP